import {ProviderModelMeta} from './types'

export default [
	{
		id: 'kilo-auto/free',
		label: 'Kilo Auto Free',
		contextWindow: '128K tokens',
		maxOutputTokens: '16K tokens',
		bestFor: ['Free tier', 'General coding', 'Quick tasks'],
		notes: 'Free auto-selected model via Kilo Gateway.',
	},
	{
		id: 'anthropic/claude-sonnet-4.5',
		label: 'Claude Sonnet 4.5 (via Kilo)',
		contextWindow: '200K tokens',
		maxOutputTokens: '8K tokens',
		bestFor: ['Coding tasks', 'Analysis', 'Agentic workflows'],
		notes: 'Routed through Kilo Gateway.',
	},
	{
		id: 'anthropic/claude-opus-4',
		label: 'Claude Opus 4 (via Kilo)',
		contextWindow: '200K tokens',
		maxOutputTokens: '32K tokens',
		bestFor: ['Deep reasoning', 'Complex planning', 'Long-form output'],
		notes: 'Routed through Kilo Gateway.',
	},
	{
		id: 'openai/gpt-4o',
		label: 'GPT-4o (via Kilo)',
		contextWindow: '128K tokens',
		maxOutputTokens: '16K tokens',
		bestFor: ['General chat', 'Code generation', 'Multimodal workflows'],
		notes: 'Routed through Kilo Gateway.',
	},
	{
		id: 'openai/gpt-4.1',
		label: 'GPT-4.1 (via Kilo)',
		contextWindow: '1M tokens',
		maxOutputTokens: '32K tokens',
		bestFor: ['Long-context coding', 'Complex reasoning', 'Tool use'],
		notes: 'Routed through Kilo Gateway.',
	},
	{
		id: 'google/gemini-2.5-pro',
		label: 'Gemini 2.5 Pro (via Kilo)',
		contextWindow: '1M tokens',
		maxOutputTokens: '64K tokens',
		bestFor: ['Complex reasoning', 'Architecture decisions', 'Long contexts'],
		notes: 'Routed through Kilo Gateway.',
	},
	{
		id: 'google/gemini-2.5-flash',
		label: 'Gemini 2.5 Flash (via Kilo)',
		contextWindow: '1M tokens',
		maxOutputTokens: '64K tokens',
		bestFor: ['Fast coding help', 'General chat', 'Tool-heavy apps'],
		notes: 'Routed through Kilo Gateway.',
	},
	{
		id: 'xai/grok-3',
		label: 'Grok 3 (via Kilo)',
		contextWindow: '128K tokens',
		maxOutputTokens: '32K tokens',
		bestFor: ['Reasoning', 'Coding', 'Analysis'],
		notes: 'Routed through Kilo Gateway.',
	},
	{
		id: 'mistral/codestral',
		label: 'Codestral (via Kilo)',
		contextWindow: '256K tokens',
		maxOutputTokens: '32K tokens',
		bestFor: ['Code generation', 'Code completion', 'FIM tasks'],
		notes: 'Mistral coding model via Kilo Gateway.',
	},
	{
		id: 'deepseek/deepseek-chat',
		label: 'DeepSeek Chat (via Kilo)',
		contextWindow: '64K tokens',
		maxOutputTokens: '8K tokens',
		bestFor: ['General coding', 'Q&A', 'Low-cost conversations'],
		notes: 'Routed through Kilo Gateway.',
	},
	{
		id: 'qwen/qwen3-coder',
		label: 'Qwen3 Coder (via Kilo)',
		contextWindow: '256K tokens',
		maxOutputTokens: '16K tokens',
		bestFor: ['Agentic coding', 'Repo-scale tasks', 'Tool use'],
		notes: 'Routed through Kilo Gateway.',
	},
] as const satisfies ProviderModelMeta[]
