import {ProviderModelMeta} from './types'

export default [
	{
		id: 'mimo-v2.5-free',
		label: 'MiMo V2.5 Free',
		contextWindow: '128K tokens',
		maxOutputTokens: '16K tokens',
		bestFor: ['Free tier coding', 'General chat', 'Quick tasks'],
		notes: 'Free model on OpenCode Zen platform.',
	},
	{
		id: 'claude-opus-4-8',
		label: 'Claude Opus 4.8',
		contextWindow: '200K tokens',
		maxOutputTokens: '32K tokens',
		bestFor: ['Deep reasoning', 'Complex planning', 'Long-form output'],
		notes: 'Latest Claude Opus via OpenCode Zen.',
	},
	{
		id: 'claude-opus-4-6',
		label: 'Claude Opus 4.6',
		contextWindow: '200K tokens',
		maxOutputTokens: '8K tokens',
		bestFor: ['Deep reasoning', 'Complex planning', 'Long-form output'],
		notes: 'High-quality Claude model.',
	},
	{
		id: 'claude-sonnet-4-6',
		label: 'Claude Sonnet 4.6',
		contextWindow: '200K tokens',
		maxOutputTokens: '8K tokens',
		bestFor: ['Coding tasks', 'Analysis', 'Agentic workflows'],
		notes: 'Default high-quality Claude option.',
	},
	{
		id: 'claude-haiku-4-5',
		label: 'Claude Haiku 4.5',
		contextWindow: '200K tokens',
		maxOutputTokens: '8K tokens',
		bestFor: ['Fast responses', 'Low-latency tasks', 'Lightweight chats'],
		notes: 'Best speed/cost profile in Claude family.',
	},
	{
		id: 'gemini-3.5-flash',
		label: 'Gemini 3.5 Flash',
		contextWindow: '1M tokens',
		maxOutputTokens: '128K tokens',
		bestFor: ['Fast coding', 'Everyday chat', 'Large-context tasks'],
		notes: 'Balanced Gemini model with strong speed.',
	},
	{
		id: 'gemini-3.1-pro',
		label: 'Gemini 3.1 Pro',
		contextWindow: '1M tokens',
		maxOutputTokens: '200K tokens',
		bestFor: ['Advanced reasoning', 'Agentic workflows', 'Complex coding'],
		notes: 'Flagship Gemini model.',
	},
	{
		id: 'gemini-3-flash',
		label: 'Gemini 3 Flash',
		contextWindow: '1M tokens',
		maxOutputTokens: '64K tokens',
		bestFor: ['Fast coding', 'Real-time apps', 'High-volume tasks'],
		notes: 'Frontier-class performance with high speed.',
	},
	{
		id: 'gpt-5.5',
		label: 'GPT-5.5',
		contextWindow: '400K tokens',
		maxOutputTokens: '128K tokens',
		bestFor: ['Agentic tasks', 'Complex reasoning', 'Coding'],
		notes: 'Latest OpenAI flagship model.',
	},
	{
		id: 'gpt-5.4',
		label: 'GPT-5.4',
		contextWindow: '1.05M tokens',
		maxOutputTokens: '128K tokens',
		bestFor: ['Agentic tasks', 'Computer use', 'Complex reasoning'],
		notes: 'Frontier model with native capabilities.',
	},
	{
		id: 'gpt-5.3-codex',
		label: 'GPT-5.3 Codex',
		contextWindow: '400K tokens',
		maxOutputTokens: '128K tokens',
		bestFor: ['Code generation', 'Repository edits', 'Agentic coding'],
		notes: 'Codex-tuned for software engineering.',
	},
	{
		id: 'deepseek-v4-pro',
		label: 'DeepSeek V4 Pro',
		contextWindow: '128K tokens',
		maxOutputTokens: '32K tokens',
		bestFor: ['Reasoning', 'Coding', 'Analysis'],
		notes: 'Advanced DeepSeek model.',
	},
	{
		id: 'deepseek-v4-flash-free',
		label: 'DeepSeek V4 Flash Free',
		contextWindow: '128K tokens',
		maxOutputTokens: '16K tokens',
		bestFor: ['Free tier', 'Quick coding', 'General chat'],
		notes: 'Free DeepSeek model on OpenCode Zen.',
	},
	{
		id: 'qwen3.6-plus',
		label: 'Qwen3.6 Plus',
		contextWindow: '256K tokens',
		maxOutputTokens: '16K tokens',
		bestFor: ['Coding', 'Reasoning', 'Agentic tasks'],
		notes: 'Latest Qwen release.',
	},
	{
		id: 'qwen3.6-plus-free',
		label: 'Qwen3.6 Plus Free',
		contextWindow: '256K tokens',
		maxOutputTokens: '16K tokens',
		bestFor: ['Free tier', 'Coding', 'General chat'],
		notes: 'Free Qwen model on OpenCode Zen.',
	},
	{
		id: 'big-pickle',
		label: 'Big Pickle',
		contextWindow: '256K tokens',
		maxOutputTokens: '32K tokens',
		bestFor: ['Experimental', 'General tasks'],
		notes: 'Experimental OpenCode model.',
	},
	{
		id: 'grok-build-0.1',
		label: 'Grok Build 0.1',
		contextWindow: '128K tokens',
		maxOutputTokens: '16K tokens',
		bestFor: ['Coding', 'Reasoning', 'General tasks'],
		notes: 'xAI Grok model via OpenCode Zen.',
	},
] as const satisfies ProviderModelMeta[]
